doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_role: App\Core\Entities\User\RoleType
            user_status: App\Core\Entities\User\StatusType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entities/User'
                prefix: 'App\Core\Entities\User'
                alias: User
            Post:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Core/Entities/Post'
                prefix: 'App\Core\Entities\Post'
                alias: Post
