version: '3'
services:
    app-nginx:
      build:
          context: ./docker/development
          dockerfile: nginx.docker
      volumes:
          - ./:/app
      depends_on:
          - app-php-fpm
      ports:
          - "8080:80"
          
    app-php-fpm:
        build:
            context: ./docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - app-postgres

    app-php-cli:
        build:
            context: ./docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
        depends_on:
            - app-postgres
        extra_hosts:
            - "mainhost:172.17.0.1"
        tty: true

    app-postgres:
        image: postgres:11.2-alpine
        volumes:
            - app-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: symfony5-app
        ports:
            - "54321:5432"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8025:8025"

volumes:
    app-postgres:
