web_frontend:
    resource: ../../src/Ui/Web/Frontend/Controllers/
    type: annotation

web_admin:
    resource: ../../src/Ui/Web/Admin/Controllers/
    prefix: /cp
    name_prefix: admin_
    type: annotation

api:
    resource: ../../src/Ui/Api/Controllers/
    prefix: /api/v1
    name_prefix: api_
    type: annotation
    defaults:
        _format: json