web:
    resource: ../../src/Ui/Web/Frontend/Controllers/
    type: annotation

api:
    resource: ../../src/Ui/Api/Controllers/
    prefix: /api/v1
    name_prefix: api_
    type: annotation
    defaults:
        _format: json